export const DETECTION_CONFIG = {
  SUPPORT_SENSITIVITY_MULTIPLIER: 1.3,
  MIN_TOUCHES: 2,
  CLUSTER_SIZE: 5,
  THRESHOLD_MULTIPLIER: 0.02,
  SUPPORT_SENSITIVITY: 0.7,
  RESISTANCE_SENSITIVITY: 0.8
};